# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 300)
        self.Timer = QtWidgets.QLabel(Dialog)
        self.Timer.setGeometry(QtCore.QRect(20, 30, 61, 16))
        self.Timer.setObjectName("Timer")
        self.setTimer = QtWidgets.QTextEdit(Dialog)
        self.setTimer.setGeometry(QtCore.QRect(100, 20, 111, 31))
        self.setTimer.setObjectName("setTimer")
        self.CurrentTimer = QtWidgets.QLabel(Dialog)
        self.CurrentTimer.setGeometry(QtCore.QRect(20, 80, 151, 31))
        self.CurrentTimer.setObjectName("CurrentTimer")
        self.cTimerValue = QtWidgets.QLabel(Dialog)
        self.cTimerValue.setGeometry(QtCore.QRect(200, 90, 54, 16))
        self.cTimerValue.setObjectName("cTimerValue")
        self.Apply = QtWidgets.QPushButton(Dialog)
        self.Apply.setGeometry(QtCore.QRect(270, 20, 75, 23))
        self.Apply.setObjectName("Apply")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Timer.setText(_translate("Dialog", "Timer"))
        self.CurrentTimer.setText(_translate("Dialog", "CurrentTimer"))
        self.cTimerValue.setText(_translate("Dialog", "0"))
        self.Apply.setText(_translate("Dialog", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
